name: Check notebooks submission
description: Check if submission material is OK

inputs:
  readme-path:
    description: Path of the README file with instructions, relative to the root of the repository
    required: false
    default: README.md

runs:
  using: composite
  steps:

  - name: Extract code blocks from markdown file
    id: extract-code
    shell: bash
    run: |
      npm install -g codedown
      codedown < "${{ inputs.readme-path }}" bash > code.sh

  - name: Run the code
    id: run-code
    shell: bash
    run: |
      cat code.sh
      bash --noprofile --norc -e -o pipefail code.sh

  - shell: bash
    run: ls -lht

  - name: Save HTML files as artifact
    uses: actions/upload-artifact@v4
    with:
      path: '**/*'
      if-no-files-found: error
      name: working-directory
