name: US-RSE'24 CI

on:

  workflow_call:
    inputs:

      notebook:
        required: true
        description: Path to the notebook file, relative to the repository root
        type: string

      repository:
        required: false
        description: Full name (owner/repo-name) to be checked
        type: string
        default: ${{ github.repository }}

      ref:
        required: false
        description: Git ref to be checked
        type: string
        default: ${{ github.ref }}

      container-registry:
        description: If set, container image will be pushed to this registry
        type: string
        required: false
        default: ghcr.io

      container-registry-username:
        description: Username to container registry
        type: string
        required: false
        default: ${{ github.actor }}

      binder-cache-branch:
        description: If set (default), the built container image will be written to .binder/Dockerfile and pushed to this branch. To disable this, set it to the empty string.
        type: string
        required: false
        default: binder-cache

      build-artifacts:
        description:
          If set, these files or directories will be extracted by the built container image and made available as GHA artifacts.
          Multiple entries are supported if a multiline string is used.
          Each line may refer to either files or directories, however wildcard patterns are NOT supported.
        type: string
        required: false
        default: ''

      test-container:
        description: Container name to use for testing the built image.
        type: string
        required: false
        default: canary

      binder-base-url:
        description: Base URL for Binderhub instance to use for launch links/buttons
        type: string
        required: false
        default: 'https://mybinder.org/v2'

    secrets:
      container-registry-password:
        description: Password to container registry
        required: false

jobs:

  info:
    name: Info
    runs-on: ubuntu-latest

    steps:

      - name: Display called workflow
        uses: actions/github-script@v7
        with:
          script: |
            const resp = await github.rest.actions.getWorkflowRun({
              run_id: context.runId,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            function parseWorkflowPath(path) {
              const regex = /^(?<repository>[\w-]+[/][\w-]+)[/](?<filepath>[^@]+)@(?<ref>\S+)$/;
              const match = path.match(regex);
              const result = match.groups;
              return result;
            }
            const runInfo = resp.data;
            for (const wf of runInfo.referenced_workflows) {
              const txt = JSON.stringify(wf, null, 4);
              core.notice(txt);
              const {path, sha} = wf;
              const {repository, filepath, ref} = parseWorkflowPath(path);
              const fileUrl = `${context.serverUrl}/${repository}/blob/${ref}/${filepath}`;
              core.summary.addRaw(`Workflow \`${filepath}\` from ${repository}@${sha} (\`${ref}\`) ([link to file](${fileUrl}))`, true);
            }
            core.summary.write()

  files:
    name: Required files
    runs-on: ubuntu-latest
    env:
      PIP_PROGRESS_BAR: 'off'

    steps:

      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
      - name: Validate notebook file
        run: |
          if [ -s "${{ inputs.notebook }}" ]; then
              echo "Notebook file is present"
          else
              echo "::error Notebook file ${{ inputs.notebook }} not found or empty"
              exit 1
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Validate citation file
        run: |
          pip install cffconvert
          cffconvert --validate

  image-build:
    name: Build image (repo2docker)
    needs: [files]
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.repo2docker.outputs.IMAGE_SHA_NAME }}
    steps:

      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Normalize repository for Docker image name compatibility
        # https://github.com/orgs/community/discussions/25768#discussioncomment-3249183
        run: |
          repository="${{ inputs.repository }}"
          echo "NORMALIZED_IMAGE_NAME=${repository@L}" >> $GITHUB_ENV

      - name: repo2docker (no push)
        uses: jupyterhub/repo2docker-action@b3cd89ff99f95b00abb5b4db27ec49bb4d3f8c85
        if: inputs.container-registry == ''
        id: repo2docker-no-push
        with:
          NO_PUSH: "true"
          IMAGE_NAME: ${{ env.NORMALIZED_IMAGE_NAME }}
          MYBINDERORG_TAG: ${{ github.sha }}

      - name: repo2docker (push)
        uses: jupyterhub/repo2docker-action@b3cd89ff99f95b00abb5b4db27ec49bb4d3f8c85
        if: inputs.container-registry
        id: repo2docker
        with:
          NO_PUSH: "false"
          DOCKER_REGISTRY: ${{ inputs.container-registry }}
          DOCKER_USERNAME: ${{ inputs.container-registry-username }}
          DOCKER_PASSWORD: ${{ secrets.container-registry-password || secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ${{ env.NORMALIZED_IMAGE_NAME }}
          MYBINDERORG_TAG: ${{ github.sha }}

  container-launch:
    name: Test container launch
    if: inputs.test-container
    runs-on: ubuntu-latest
    needs: [image-build]
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.container-registry }}
          username: ${{ inputs.container-registry-username }}
          password: ${{ secrets.container-registry-password || secrets.GITHUB_TOKEN }}

      - name: Run command to test built image ${{ needs.image-build.outputs.image }}
        id: run
        run: |
          canary_command="ls -la"
          docker run --name "${{ inputs.test-container }}" "${{ needs.image-build.outputs.image }}" $canary_command

      - name: Copy artifacts from container
        id: copy
        run: |
          stuff_to_copy="${{ inputs.build-artifacts }}"
          container_working_dir=$(docker inspect --format '{{.Config.WorkingDir}}' "${{ inputs.test-container }}")

          for file_or_dir in $stuff_to_copy
          do
              docker cp "${{ inputs.test-container }}:${container_working_dir}/${file_or_dir}" "./${file_or_dir}"
          done

          # delete container once done
          docker rm --volumes "${{ inputs.test-container }}"

      - name: Upload copied build artifacts
        if: inputs.build-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ inputs.build-artifacts }}
          if-no-files-found: error
        id: upload-build-artifacts

  binder-cache:
    runs-on: ubuntu-latest
    if: inputs.binder-cache-branch
    needs: [image-build]
    outputs:
      ref: ${{ steps.update-repo.outputs.branch-name }}
    steps:

      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Update repo with Binder cache branch
        id: update-repo
        run: |
          branch_name="${{ inputs.binder-cache-branch }}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global push.autoSetupRemote true
          git switch --force-create "$branch_name"
          mkdir -p .binder

          cat << 'EOF' > .binder/Dockerfile
          FROM ${{ needs.image-build.outputs.image }}
          EOF

          git add .binder/Dockerfile
          git commit -m "Update image tag"
          git push -f
          echo "branch-name=$branch_name" >> $GITHUB_OUTPUT

  report:
    name: Report status
    needs: [image-build, container-launch, binder-cache]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    env:
      RESOURCES_REPO_URL: ${{ github.server_url }}/USRSE/notebooks-submissions
      DOCS_URL: ${{ github.server_url }}/USRSE/notebooks-submissions/blob/main/docs
      SLACK_URL: https://usrse.slack.com/archives/C060Z8034MU
    steps:

      - name: Report build failure
        if: ${{ !( needs.image-build.result == 'success' && needs.container-launch.result == 'success') }}
        run: |
          cat << 'EOF' > $GITHUB_STEP_SUMMARY
          The CI run was not successful for ${{ inputs.repository }}@${{ inputs.ref }}.

          See the following resources for details:
          
          - [Notebooks CI repository](${{ env.RESOURCES_REPO_URL }})
          - [Notebooks CI troubleshooting](${{ env.DOCS_URL }}/troubleshooting.md)
          - [Notebooks CI documentation](${{ env.DOCS_URL }})
          - [Notebooks CI wiki](${{ env.RESOURCES_REPO_URL }}/wiki)
          - [`#usrse24` channel](${{ env.SLACK_URL }}) on the US-RSE Slack workspace

          EOF

      - name: Report build success
        if:  needs.image-build.result == 'success' && needs.container-launch.result == 'success'
        run: |
          cat << 'EOF' >> $GITHUB_STEP_SUMMARY
          The CI build was successful for ${{ inputs.repository }}@${{ inputs.ref }}!

          EOF

      - name: Add Binder launch (w/ cache)
        if: needs.binder-cache.result == 'success'
        run: |
          cat << 'EOF' >> $GITHUB_STEP_SUMMARY
          [![Binder](https://mybinder.org/badge_logo.svg)](${{ inputs.binder-base-url }}/gh/${{ inputs.repository }}/${{ needs.binder-cache.outputs.ref }}) :point_left: Launch Binder from ${{ inputs.repository }}@${{ needs.binder-cache.outputs.ref }} (faster)
          EOF

      - name: Add Binder launch
        run: |
          cat << 'EOF' >> $GITHUB_STEP_SUMMARY
          [![Binder](https://mybinder.org/badge_logo.svg)](${{ inputs.binder-base-url }}/gh/${{ inputs.repository }}/${{ inputs.ref}}) :point_left: Launch Binder from ${{ inputs.repository }}@${{ inputs.ref }} (needs rebuild)
          EOF
