on:

  workflow_call:
    inputs:

      repository:
        required: true
        description: Full name (owner/repo-name) to be checked
        type: string

      ref:
        required: true
        description: Git ref to be checked
        type: string

      reproducible-document:
        required: false
        description: Path to reproducible document, if any
        default: ''
        type: string

      quarto-render-args:
        required: false
        description: Extra args/options for the quarto render command
        default: --to html -M self-contained:true --execute
        type: string

  workflow_dispatch:
    inputs:

      repository:
        required: true
        description: Full name (owner/repo-name) to be checked
        type: string

      ref:
        required: true
        description: Git ref to be checked
        type: string

      reproducible-document:
        required: false
        description: Path to reproducible document, if any
        default: ''
        type: string

      quarto-render-args:
        required: false
        description: Extra args/options for the quarto render command
        default: --to html -M self-contained:true --execute
        type: string

jobs:

  repo2docker-build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Run quarto render
        if: inputs.reproducible-document
        run: |
          cat << 'EOF' >> postBuild
          #!/bin/bash
          set -e
          set -o pipefail
          quarto render "${{ inputs.reproducible-document }}" ${{ inputs.quarto-render-args }}
          EOF

      - uses: jupyterhub/repo2docker-action@b3cd89ff99f95b00abb5b4db27ec49bb4d3f8c85
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ inputs.ref }}
