name: US-RSE'24 CI

on:

  workflow_call:
    inputs:

      repository:
        required: true
        description: Full name (owner/repo-name) to be checked
        type: string

      ref:
        required: true
        description: Git ref to be checked
        type: string

      reproducible-document:
        required: false
        description: Path to reproducible document, if any
        default: ''
        type: string

      quarto-render-args:
        required: false
        description: Extra args/options for the quarto render command
        default: --to html -M self-contained:true --execute
        type: string

      container-registry:
        description: If set, container image will be pushed to this registry
        type: string
        required: false
        default: ghcr.io

      binder-cache-branch:
        description: If set (default), the built container image will be written to .binder/Dockerfile and pushed to this branch. To disable this, set it to the empty string.
        type: string
        required: false
        default: binder-cache

      build-artifacts:
        description:
          If set, these files or directories will be extracted by the built container image and made available as GHA artifacts.
          Multiple entries are supported if a multiline string is used.
          Each line may refer to either files or directories, however wildcard patterns are NOT supported.
        type: string
        required: false
        default: ''

      test-container:
        description: Container name to use for testing the built image.
        type: string
        required: false
        default: canary

      binder-base-url:
        description: Base URL for Binderhub instance to use for launch links/buttons
        type: string
        required: false
        default: 'https://mybinder.org/v2'

jobs:

  info:
    name: Info about the workflow run
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Called workflow info
        run: |
          wf_info=$(
            gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            --jq '.referenced_workflows'
          )
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo "$wf_info" | jq >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Called workflow info using JS
        uses: actions/github-script@v7
        with:
          script: |
            const resp = await github.rest.actions.getWorkflowRun({
              run_id: context.runId,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const runInfo = resp.data;
            for (const wf of runInfo.referenced_workflows) {
              const txt = JSON.stringify(wf, null, 4);
              core.notice(txt);
              core.summary.addCodeBlock(txt, 'json');
              core.summary.addRaw(wf.path, true);
            }
            core.summary.write()
