name: Test this repository

on:
  push:

jobs:

  test-action:

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: lbianchi-lbl/notebooks-ci@main
        with:
          readme-path: README.md

  test-with-sample-repo:
    name: Test using sample repo (${{ matrix.repository }}@${{ matrix.ref }})
    strategy:
      fail-fast: false
      matrix:
        repository:
          - lbianchi-lbl/sample-submission-1
        workflow-under-test:
          - ${{ github.repository }}/.github/workflows/check-submission.yml
        ref:
          - main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}
          ref: ${{ matrix.ref }}
      - name: Update references to workflow under test with current commit
        run: |
          git log -n 1
          sed -i 's#^\(    uses: ${{ matrix.workflow-under-test }}\)\(@[^[:space:]]*\)#\1@${{ github.sha }}#' .github/workflows/*.yml
          git status -v
