name: Test this repository

on:
  push:

env:
  FORCE_COLOR: "yes"

jobs:

  test-with-sample-repo:
    name: Test using sample repo (${{ matrix.repository }}@${{ matrix.ref }})
    strategy:
      fail-fast: false
      matrix:
        repository:
          - lbianchi-lbl/sample-submission-1
        workflow-under-test:
          - ${{ github.repository }}/.github/workflows/check-submission.yml
        ref:
          - main
    runs-on: ubuntu-latest
    steps:
      - name: Define extra metadata
        run: |
          WORKFLOW_SHORT_SHA="$(echo ${{ github.sha }} | cut -c 1-7)"
          WORKFLOW_SHORT_LINK="${{ github.repository }}@${WORKFLOW_SHORT_SHA}"
          WORKFLOW_FULL_LINK="${{ matrix.workflow-under-test }}@${{ github.sha }}"

          echo "WORKFLOW_SHORT_SHA=$WORKFLOW_SHORT_SHA" >> $GITHUB_ENV
          echo "WORKFLOW_SHORT_LINK=$WORKFLOW_SHORT_LINK" >> $GITHUB_ENV
          echo "WORKFLOW_FULL_LINK=$WORKFLOW_FULL_LINK" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}
          ref: ${{ matrix.ref }}
          token: ${{ secrets.CLIENT_REPO_TOKEN }}
      - name: Update references to workflow under test with current commit
        run: |
          git log -n 1
          sed -i 's#^\(    uses: ${{ matrix.workflow-under-test }}\)\(@[^[:space:]]*\)#\1@${{ github.sha }}#' .github/workflows/*.yml
          git status -vv
      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global push.autoSetupRemote true
          git add .github/workflows/*.yml
          git status -vv
          git commit -m "Test $WORKFLOW_SHORT_LINK" -m "Test $WORKFLOW_FULL_LINK"
          git push -f
